export type EmailCategory = "personal" | "agency";

// Consumer mailbox domains stay explicit so custom domains remain agency contacts.
const personalEmailDomains = new Set([
  "gmail.com",
  "googlemail.com",
  "outlook.com",
  "outlook.co.uk",
  "outlook.de",
  "outlook.fr",
  "hotmail.com",
  "hotmail.co.uk",
  "hotmail.de",
  "hotmail.fr",
  "live.com",
  "live.co.uk",
  "live.de",
  "live.fr",
  "live.it",
  "live.nl",
  "msn.com",
  "icloud.com",
  "me.com",
  "mac.com",
  "yahoo.com",
  "yahoo.co.uk",
  "yahoo.ca",
  "yahoo.com.au",
  "yahoo.de",
  "yahoo.fr",
  "yahoo.it",
  "yahoo.es",
  "yahoo.co.in",
  "yahoo.in",
  "yahoo.co.jp",
  "yahoo.com.br",
  "yahoo.com.mx",
  "yahoo.com.sg",
  "yahoo.com.ph",
  "yahoo.co.th",
  "ymail.com",
  "rocketmail.com",
  "aol.com",
  "aim.com",
  "proton.me",
  "protonmail.com",
  "protonmail.ch",
  "pm.me",
  "gmx.com",
  "gmx.net",
  "gmx.de",
  "gmx.at",
  "gmx.ch",
  "gmx.fr",
  "gmx.us",
  "mail.com",
  "email.com",
  "usa.com",
  "myself.com",
  "post.com",
  "europe.com",
  "asia.com",
  "consultant.com",
  "engineer.com",
  "techie.com",
  "accountant.com",
  "lawyer.com",
  "writeme.com",
  "zoho.com",
  "zohomail.com",
  "fastmail.com",
  "fastmail.fm",
  "tuta.com",
  "tuta.io",
  "tutanota.com",
  "tutanota.de",
  "tutamail.com",
  "keemail.me",
  "hey.com",
  "hushmail.com",
  "mailfence.com",
  "mailbox.org",
  "posteo.de",
  "runbox.com",
  "yandex.com",
  "yandex.ru",
  "ya.ru",
  "mail.ru",
  "inbox.ru",
  "list.ru",
  "bk.ru",
  "rambler.ru",
  "ukr.net",
  "inbox.lv",
  "qq.com",
  "foxmail.com",
  "163.com",
  "126.com",
  "yeah.net",
  "sina.com",
  "sohu.com",
  "naver.com",
  "daum.net",
  "hanmail.net",
  "rediffmail.com",
  "seznam.cz",
  "centrum.cz",
  "web.de",
  "freenet.de",
  "t-online.de",
  "orange.fr",
  "wanadoo.fr",
  "laposte.net",
  "libero.it",
  "virgilio.it",
  "uol.com.br",
  "bol.com.br",
  "terra.com.br",
  "wp.pl",
  "onet.pl",
  "interia.pl",
  "abv.bg",
  "mail.bg",
  "btinternet.com",
  "sky.com",
  "comcast.net",
  "xfinity.com",
  "verizon.net",
  "att.net",
  "sbcglobal.net",
  "bellsouth.net",
  "shaw.ca",
  "rogers.com",
  "telus.net",
]);

const emailPattern = /[A-Z0-9._%+-]+@([A-Z0-9.-]+\.[A-Z]{2,})/gi;

export function extractEmailAddresses(value: string): string[] {
  const matches = value.match(emailPattern) ?? [];
  return Array.from(new Set(matches.map((email) => email.toLowerCase())));
}

export function classifyEmailAddress(email: string): EmailCategory | undefined {
  const domain = email.trim().toLowerCase().split("@").pop();
  if (!domain || !domain.includes(".")) return undefined;
  return personalEmailDomains.has(domain) ? "personal" : "agency";
}

export function classifyEmailText(value: string): Set<EmailCategory> {
  return new Set(
    extractEmailAddresses(value)
      .map(classifyEmailAddress)
      .filter((category): category is EmailCategory => Boolean(category)),
  );
}
