/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as PromptVaultRouteImport } from './routes/prompt-vault'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HelpRouteImport } from './routes/help'
import { Route as EmployeeProfileRouteImport } from './routes/employee-profile'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as CreatorSourcingRouteImport } from './routes/creator-sourcing'
import { Route as CreatorOutreachRouteImport } from './routes/creator-outreach'
import { Route as CampaignProfilesRouteImport } from './routes/campaign-profiles'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ActiveCampaignsRouteImport } from './routes/active-campaigns'
import { Route as AboutKatlasMediaRouteImport } from './routes/about-katlas-media'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActiveCampaignsIndexRouteImport } from './routes/active-campaigns.index'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'
import { Route as ApiBulkSenderRouteImport } from './routes/api/bulk-sender'
import { Route as ActiveCampaignsCampaignIdRouteImport } from './routes/active-campaigns.$campaignId'
import { Route as ApiSourcingTiktokProfilesRouteImport } from './routes/api/sourcing/tiktok-profiles'
import { Route as ApiSourcingHashtagRouteImport } from './routes/api/sourcing/hashtag'
import { Route as ApiCalendarWebhookRouteImport } from './routes/api/calendar/webhook'
import { Route as ApiCalendarNotificationsRouteImport } from './routes/api/calendar/notifications'
import { Route as ApiCalendarCronRouteImport } from './routes/api/calendar/cron'
import { Route as ApiCalendarConnectionRouteImport } from './routes/api/calendar/connection'
import { Route as ApiAiOutreachRouteImport } from './routes/api/ai/outreach'
import { Route as ApiAiEnrichContactsRouteImport } from './routes/api/ai/enrich-contacts'
import { Route as ApiCalendarOauthStartRouteImport } from './routes/api/calendar/oauth/start'
import { Route as ApiCalendarOauthCallbackRouteImport } from './routes/api/calendar/oauth/callback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptVaultRoute = PromptVaultRouteImport.update({
  id: '/prompt-vault',
  path: '/prompt-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/employee-profile',
  path: '/employee-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSourcingRoute = CreatorSourcingRouteImport.update({
  id: '/creator-sourcing',
  path: '/creator-sourcing',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorOutreachRoute = CreatorOutreachRouteImport.update({
  id: '/creator-outreach',
  path: '/creator-outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignProfilesRoute = CampaignProfilesRouteImport.update({
  id: '/campaign-profiles',
  path: '/campaign-profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveCampaignsRoute = ActiveCampaignsRouteImport.update({
  id: '/active-campaigns',
  path: '/active-campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutKatlasMediaRoute = AboutKatlasMediaRouteImport.update({
  id: '/about-katlas-media',
  path: '/about-katlas-media',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveCampaignsIndexRoute = ActiveCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ActiveCampaignsRoute,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBulkSenderRoute = ApiBulkSenderRouteImport.update({
  id: '/api/bulk-sender',
  path: '/api/bulk-sender',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveCampaignsCampaignIdRoute =
  ActiveCampaignsCampaignIdRouteImport.update({
    id: '/$campaignId',
    path: '/$campaignId',
    getParentRoute: () => ActiveCampaignsRoute,
  } as any)
const ApiSourcingTiktokProfilesRoute =
  ApiSourcingTiktokProfilesRouteImport.update({
    id: '/api/sourcing/tiktok-profiles',
    path: '/api/sourcing/tiktok-profiles',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSourcingHashtagRoute = ApiSourcingHashtagRouteImport.update({
  id: '/api/sourcing/hashtag',
  path: '/api/sourcing/hashtag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarWebhookRoute = ApiCalendarWebhookRouteImport.update({
  id: '/api/calendar/webhook',
  path: '/api/calendar/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarNotificationsRoute =
  ApiCalendarNotificationsRouteImport.update({
    id: '/api/calendar/notifications',
    path: '/api/calendar/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCalendarCronRoute = ApiCalendarCronRouteImport.update({
  id: '/api/calendar/cron',
  path: '/api/calendar/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarConnectionRoute = ApiCalendarConnectionRouteImport.update({
  id: '/api/calendar/connection',
  path: '/api/calendar/connection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiOutreachRoute = ApiAiOutreachRouteImport.update({
  id: '/api/ai/outreach',
  path: '/api/ai/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiEnrichContactsRoute = ApiAiEnrichContactsRouteImport.update({
  id: '/api/ai/enrich-contacts',
  path: '/api/ai/enrich-contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarOauthStartRoute = ApiCalendarOauthStartRouteImport.update({
  id: '/api/calendar/oauth/start',
  path: '/api/calendar/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarOauthCallbackRoute =
  ApiCalendarOauthCallbackRouteImport.update({
    id: '/api/calendar/oauth/callback',
    path: '/api/calendar/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-katlas-media': typeof AboutKatlasMediaRoute
  '/active-campaigns': typeof ActiveCampaignsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/campaign-profiles': typeof CampaignProfilesRoute
  '/creator-outreach': typeof CreatorOutreachRoute
  '/creator-sourcing': typeof CreatorSourcingRoute
  '/deals': typeof DealsRoute
  '/employee-profile': typeof EmployeeProfileRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/outreach': typeof OutreachRoute
  '/prompt-vault': typeof PromptVaultRoute
  '/roster': typeof RosterRoute
  '/settings': typeof SettingsRoute
  '/active-campaigns/$campaignId': typeof ActiveCampaignsCampaignIdRoute
  '/api/bulk-sender': typeof ApiBulkSenderRoute
  '/api/translate': typeof ApiTranslateRoute
  '/active-campaigns/': typeof ActiveCampaignsIndexRoute
  '/api/ai/enrich-contacts': typeof ApiAiEnrichContactsRoute
  '/api/ai/outreach': typeof ApiAiOutreachRoute
  '/api/calendar/connection': typeof ApiCalendarConnectionRoute
  '/api/calendar/cron': typeof ApiCalendarCronRoute
  '/api/calendar/notifications': typeof ApiCalendarNotificationsRoute
  '/api/calendar/webhook': typeof ApiCalendarWebhookRoute
  '/api/sourcing/hashtag': typeof ApiSourcingHashtagRoute
  '/api/sourcing/tiktok-profiles': typeof ApiSourcingTiktokProfilesRoute
  '/api/calendar/oauth/callback': typeof ApiCalendarOauthCallbackRoute
  '/api/calendar/oauth/start': typeof ApiCalendarOauthStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-katlas-media': typeof AboutKatlasMediaRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/campaign-profiles': typeof CampaignProfilesRoute
  '/creator-outreach': typeof CreatorOutreachRoute
  '/creator-sourcing': typeof CreatorSourcingRoute
  '/deals': typeof DealsRoute
  '/employee-profile': typeof EmployeeProfileRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/outreach': typeof OutreachRoute
  '/prompt-vault': typeof PromptVaultRoute
  '/roster': typeof RosterRoute
  '/settings': typeof SettingsRoute
  '/active-campaigns/$campaignId': typeof ActiveCampaignsCampaignIdRoute
  '/api/bulk-sender': typeof ApiBulkSenderRoute
  '/api/translate': typeof ApiTranslateRoute
  '/active-campaigns': typeof ActiveCampaignsIndexRoute
  '/api/ai/enrich-contacts': typeof ApiAiEnrichContactsRoute
  '/api/ai/outreach': typeof ApiAiOutreachRoute
  '/api/calendar/connection': typeof ApiCalendarConnectionRoute
  '/api/calendar/cron': typeof ApiCalendarCronRoute
  '/api/calendar/notifications': typeof ApiCalendarNotificationsRoute
  '/api/calendar/webhook': typeof ApiCalendarWebhookRoute
  '/api/sourcing/hashtag': typeof ApiSourcingHashtagRoute
  '/api/sourcing/tiktok-profiles': typeof ApiSourcingTiktokProfilesRoute
  '/api/calendar/oauth/callback': typeof ApiCalendarOauthCallbackRoute
  '/api/calendar/oauth/start': typeof ApiCalendarOauthStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-katlas-media': typeof AboutKatlasMediaRoute
  '/active-campaigns': typeof ActiveCampaignsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/campaign-profiles': typeof CampaignProfilesRoute
  '/creator-outreach': typeof CreatorOutreachRoute
  '/creator-sourcing': typeof CreatorSourcingRoute
  '/deals': typeof DealsRoute
  '/employee-profile': typeof EmployeeProfileRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/outreach': typeof OutreachRoute
  '/prompt-vault': typeof PromptVaultRoute
  '/roster': typeof RosterRoute
  '/settings': typeof SettingsRoute
  '/active-campaigns/$campaignId': typeof ActiveCampaignsCampaignIdRoute
  '/api/bulk-sender': typeof ApiBulkSenderRoute
  '/api/translate': typeof ApiTranslateRoute
  '/active-campaigns/': typeof ActiveCampaignsIndexRoute
  '/api/ai/enrich-contacts': typeof ApiAiEnrichContactsRoute
  '/api/ai/outreach': typeof ApiAiOutreachRoute
  '/api/calendar/connection': typeof ApiCalendarConnectionRoute
  '/api/calendar/cron': typeof ApiCalendarCronRoute
  '/api/calendar/notifications': typeof ApiCalendarNotificationsRoute
  '/api/calendar/webhook': typeof ApiCalendarWebhookRoute
  '/api/sourcing/hashtag': typeof ApiSourcingHashtagRoute
  '/api/sourcing/tiktok-profiles': typeof ApiSourcingTiktokProfilesRoute
  '/api/calendar/oauth/callback': typeof ApiCalendarOauthCallbackRoute
  '/api/calendar/oauth/start': typeof ApiCalendarOauthStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-katlas-media'
    | '/active-campaigns'
    | '/analytics'
    | '/calendar'
    | '/campaign-profiles'
    | '/creator-outreach'
    | '/creator-sourcing'
    | '/deals'
    | '/employee-profile'
    | '/help'
    | '/inbox'
    | '/outreach'
    | '/prompt-vault'
    | '/roster'
    | '/settings'
    | '/active-campaigns/$campaignId'
    | '/api/bulk-sender'
    | '/api/translate'
    | '/active-campaigns/'
    | '/api/ai/enrich-contacts'
    | '/api/ai/outreach'
    | '/api/calendar/connection'
    | '/api/calendar/cron'
    | '/api/calendar/notifications'
    | '/api/calendar/webhook'
    | '/api/sourcing/hashtag'
    | '/api/sourcing/tiktok-profiles'
    | '/api/calendar/oauth/callback'
    | '/api/calendar/oauth/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-katlas-media'
    | '/analytics'
    | '/calendar'
    | '/campaign-profiles'
    | '/creator-outreach'
    | '/creator-sourcing'
    | '/deals'
    | '/employee-profile'
    | '/help'
    | '/inbox'
    | '/outreach'
    | '/prompt-vault'
    | '/roster'
    | '/settings'
    | '/active-campaigns/$campaignId'
    | '/api/bulk-sender'
    | '/api/translate'
    | '/active-campaigns'
    | '/api/ai/enrich-contacts'
    | '/api/ai/outreach'
    | '/api/calendar/connection'
    | '/api/calendar/cron'
    | '/api/calendar/notifications'
    | '/api/calendar/webhook'
    | '/api/sourcing/hashtag'
    | '/api/sourcing/tiktok-profiles'
    | '/api/calendar/oauth/callback'
    | '/api/calendar/oauth/start'
  id:
    | '__root__'
    | '/'
    | '/about-katlas-media'
    | '/active-campaigns'
    | '/analytics'
    | '/calendar'
    | '/campaign-profiles'
    | '/creator-outreach'
    | '/creator-sourcing'
    | '/deals'
    | '/employee-profile'
    | '/help'
    | '/inbox'
    | '/outreach'
    | '/prompt-vault'
    | '/roster'
    | '/settings'
    | '/active-campaigns/$campaignId'
    | '/api/bulk-sender'
    | '/api/translate'
    | '/active-campaigns/'
    | '/api/ai/enrich-contacts'
    | '/api/ai/outreach'
    | '/api/calendar/connection'
    | '/api/calendar/cron'
    | '/api/calendar/notifications'
    | '/api/calendar/webhook'
    | '/api/sourcing/hashtag'
    | '/api/sourcing/tiktok-profiles'
    | '/api/calendar/oauth/callback'
    | '/api/calendar/oauth/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutKatlasMediaRoute: typeof AboutKatlasMediaRoute
  ActiveCampaignsRoute: typeof ActiveCampaignsRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  CalendarRoute: typeof CalendarRoute
  CampaignProfilesRoute: typeof CampaignProfilesRoute
  CreatorOutreachRoute: typeof CreatorOutreachRoute
  CreatorSourcingRoute: typeof CreatorSourcingRoute
  DealsRoute: typeof DealsRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  HelpRoute: typeof HelpRoute
  InboxRoute: typeof InboxRoute
  OutreachRoute: typeof OutreachRoute
  PromptVaultRoute: typeof PromptVaultRoute
  RosterRoute: typeof RosterRoute
  SettingsRoute: typeof SettingsRoute
  ApiBulkSenderRoute: typeof ApiBulkSenderRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
  ApiAiEnrichContactsRoute: typeof ApiAiEnrichContactsRoute
  ApiAiOutreachRoute: typeof ApiAiOutreachRoute
  ApiCalendarConnectionRoute: typeof ApiCalendarConnectionRoute
  ApiCalendarCronRoute: typeof ApiCalendarCronRoute
  ApiCalendarNotificationsRoute: typeof ApiCalendarNotificationsRoute
  ApiCalendarWebhookRoute: typeof ApiCalendarWebhookRoute
  ApiSourcingHashtagRoute: typeof ApiSourcingHashtagRoute
  ApiSourcingTiktokProfilesRoute: typeof ApiSourcingTiktokProfilesRoute
  ApiCalendarOauthCallbackRoute: typeof ApiCalendarOauthCallbackRoute
  ApiCalendarOauthStartRoute: typeof ApiCalendarOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-vault': {
      id: '/prompt-vault'
      path: '/prompt-vault'
      fullPath: '/prompt-vault'
      preLoaderRoute: typeof PromptVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-profile': {
      id: '/employee-profile'
      path: '/employee-profile'
      fullPath: '/employee-profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-sourcing': {
      id: '/creator-sourcing'
      path: '/creator-sourcing'
      fullPath: '/creator-sourcing'
      preLoaderRoute: typeof CreatorSourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-outreach': {
      id: '/creator-outreach'
      path: '/creator-outreach'
      fullPath: '/creator-outreach'
      preLoaderRoute: typeof CreatorOutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign-profiles': {
      id: '/campaign-profiles'
      path: '/campaign-profiles'
      fullPath: '/campaign-profiles'
      preLoaderRoute: typeof CampaignProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active-campaigns': {
      id: '/active-campaigns'
      path: '/active-campaigns'
      fullPath: '/active-campaigns'
      preLoaderRoute: typeof ActiveCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-katlas-media': {
      id: '/about-katlas-media'
      path: '/about-katlas-media'
      fullPath: '/about-katlas-media'
      preLoaderRoute: typeof AboutKatlasMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active-campaigns/': {
      id: '/active-campaigns/'
      path: '/'
      fullPath: '/active-campaigns/'
      preLoaderRoute: typeof ActiveCampaignsIndexRouteImport
      parentRoute: typeof ActiveCampaignsRoute
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bulk-sender': {
      id: '/api/bulk-sender'
      path: '/api/bulk-sender'
      fullPath: '/api/bulk-sender'
      preLoaderRoute: typeof ApiBulkSenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active-campaigns/$campaignId': {
      id: '/active-campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/active-campaigns/$campaignId'
      preLoaderRoute: typeof ActiveCampaignsCampaignIdRouteImport
      parentRoute: typeof ActiveCampaignsRoute
    }
    '/api/sourcing/tiktok-profiles': {
      id: '/api/sourcing/tiktok-profiles'
      path: '/api/sourcing/tiktok-profiles'
      fullPath: '/api/sourcing/tiktok-profiles'
      preLoaderRoute: typeof ApiSourcingTiktokProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sourcing/hashtag': {
      id: '/api/sourcing/hashtag'
      path: '/api/sourcing/hashtag'
      fullPath: '/api/sourcing/hashtag'
      preLoaderRoute: typeof ApiSourcingHashtagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/webhook': {
      id: '/api/calendar/webhook'
      path: '/api/calendar/webhook'
      fullPath: '/api/calendar/webhook'
      preLoaderRoute: typeof ApiCalendarWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/notifications': {
      id: '/api/calendar/notifications'
      path: '/api/calendar/notifications'
      fullPath: '/api/calendar/notifications'
      preLoaderRoute: typeof ApiCalendarNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/cron': {
      id: '/api/calendar/cron'
      path: '/api/calendar/cron'
      fullPath: '/api/calendar/cron'
      preLoaderRoute: typeof ApiCalendarCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/connection': {
      id: '/api/calendar/connection'
      path: '/api/calendar/connection'
      fullPath: '/api/calendar/connection'
      preLoaderRoute: typeof ApiCalendarConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/outreach': {
      id: '/api/ai/outreach'
      path: '/api/ai/outreach'
      fullPath: '/api/ai/outreach'
      preLoaderRoute: typeof ApiAiOutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/enrich-contacts': {
      id: '/api/ai/enrich-contacts'
      path: '/api/ai/enrich-contacts'
      fullPath: '/api/ai/enrich-contacts'
      preLoaderRoute: typeof ApiAiEnrichContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/oauth/start': {
      id: '/api/calendar/oauth/start'
      path: '/api/calendar/oauth/start'
      fullPath: '/api/calendar/oauth/start'
      preLoaderRoute: typeof ApiCalendarOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/oauth/callback': {
      id: '/api/calendar/oauth/callback'
      path: '/api/calendar/oauth/callback'
      fullPath: '/api/calendar/oauth/callback'
      preLoaderRoute: typeof ApiCalendarOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ActiveCampaignsRouteChildren {
  ActiveCampaignsCampaignIdRoute: typeof ActiveCampaignsCampaignIdRoute
  ActiveCampaignsIndexRoute: typeof ActiveCampaignsIndexRoute
}

const ActiveCampaignsRouteChildren: ActiveCampaignsRouteChildren = {
  ActiveCampaignsCampaignIdRoute: ActiveCampaignsCampaignIdRoute,
  ActiveCampaignsIndexRoute: ActiveCampaignsIndexRoute,
}

const ActiveCampaignsRouteWithChildren = ActiveCampaignsRoute._addFileChildren(
  ActiveCampaignsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutKatlasMediaRoute: AboutKatlasMediaRoute,
  ActiveCampaignsRoute: ActiveCampaignsRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  CalendarRoute: CalendarRoute,
  CampaignProfilesRoute: CampaignProfilesRoute,
  CreatorOutreachRoute: CreatorOutreachRoute,
  CreatorSourcingRoute: CreatorSourcingRoute,
  DealsRoute: DealsRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
  HelpRoute: HelpRoute,
  InboxRoute: InboxRoute,
  OutreachRoute: OutreachRoute,
  PromptVaultRoute: PromptVaultRoute,
  RosterRoute: RosterRoute,
  SettingsRoute: SettingsRoute,
  ApiBulkSenderRoute: ApiBulkSenderRoute,
  ApiTranslateRoute: ApiTranslateRoute,
  ApiAiEnrichContactsRoute: ApiAiEnrichContactsRoute,
  ApiAiOutreachRoute: ApiAiOutreachRoute,
  ApiCalendarConnectionRoute: ApiCalendarConnectionRoute,
  ApiCalendarCronRoute: ApiCalendarCronRoute,
  ApiCalendarNotificationsRoute: ApiCalendarNotificationsRoute,
  ApiCalendarWebhookRoute: ApiCalendarWebhookRoute,
  ApiSourcingHashtagRoute: ApiSourcingHashtagRoute,
  ApiSourcingTiktokProfilesRoute: ApiSourcingTiktokProfilesRoute,
  ApiCalendarOauthCallbackRoute: ApiCalendarOauthCallbackRoute,
  ApiCalendarOauthStartRoute: ApiCalendarOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
